notifications:
  email: false
  
language: python

python:
  - "2.7"
  
before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y libspatialite5
    #- sudo apt-get install -y osmctools
    - sudo apt-get install -y python-software-properties
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
    # postgis from pgdg requires different gdal package than the grass package
    - sudo rm -f /etc/apt/sources.list.d/pgdg-source.list 
    - sudo apt-get update -qq
    - sudo apt-get remove postgresql-9.1-postgis-2.1
    - sudo apt-get install postgresql-9.3
    - sudo apt-get install -y postgis postgresql-9.3-postgis-2.1
    - sudo apt-get install postgresql-9.3-postgis-scripts
    - sudo apt-get install -y gdal-bin libgdal-dev
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
  
before_script:
    - createuser hot --superuser --createdb -U postgres
    
# command to install dependencies

install: "pip install -r requirements-dev.txt"

# command to run tests
script: ./manage.py test


  